env: "local"

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "pgAdmin"
  dbname: "test"
  sslmode: "disable"

jwt_ttl_duration: "15m"
signing_key: "xdd"